version = 0.1

[sam-config-env.deploy.parameters]
stack_name = "aws-lambda-crawler"
	# We specify --s3-bucket explicitly in CI/deploy scripts; disable resolve_s3
	resolve_s3 = false
	s3_prefix = "aws-lambda-crawler"
region = "ap-southeast-2"
profile = "my-aws-profile"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.deploy.parameters]
stack_name = "aws-lambda-crawler"
	resolve_s3 = false
s3_prefix = "aws-lambda-crawler"
region = "ap-southeast-2"
profile = "my-aws-profile"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
	parameter_overrides = "ConfluenceSecretName=\"arn:aws:secretsmanager:ap-southeast-2:922523344160:secret:confluence/cred-tHwA8U\" S3UploadBucket=\"bytescribe-image-audio-bucket\" S3UploadPrefix=\"media-uploads\""
